# Credits: Henry Misc @ https://www.youtube.com/watch?v=v2S18Xf2PRo

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$kubernetes\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'nord'

[fill]
symbol = ' '

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Pictures' = ' '

[git_branch]
style = 'fg:purple'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'

[aws]
symbol = ' '
style = 'yellow'
format = '[$symbol($profile)(/$region )(\[$duration\] )]($style)'

[aws.region_aliases]
ap-south-1 = 'aps1'
us-east-1 = 'use1'
eu-west-1 = 'euw1'

[kubernetes]
disabled = false
symbol = '☸'
format = '[$symbol](dark_blue) [$context( \($namespace\)) ]($style)'
style = 'green'
detect_files = ['k8s-starship']

[[kubernetes.contexts]]
# Using capture groups
# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
context_pattern = 'arn:aws:eks:(?P<region>[\w-]+):(?P<account>[\d]{12}):cluster\/(?P<cluster>[\w-]+)'
context_alias = '$cluster/$region'

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style) '
pyenv_version_name = true
pyenv_prefix = ''

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[cmd_duration]
min_time = 500
style = 'fg:gray'
format = '[$duration]($style)'

[lua]
symbol = ' '

[nodejs]
style = 'blue'
symbol = ' '
format = '[$symbol($version )]($style)'

[golang]
style = 'dark_blue'
symbol = ' '
format = '[$symbol($version )]($style)'

[haskell]
style = 'blue'
symbol = ' '

[rust]
style = 'orange'
symbol = ' '

[ruby]
style = 'blue'
symbol = ' '

[package]
symbol = '󰏗 '

[docker_context]
symbol = ' '
style = 'fg:#06969A'
format = '[$symbol]($style) $path'
detect_files = ['docker-compose.yml', 'docker-compose.yaml', 'Dockerfile']
detect_extensions = ['Dockerfile']

[hostname]
ssh_only = true
format = "[$hostname]($style)"
trim_at = "-"
style = "bold dimmed white"
disabled = false

[sudo]
style = 'bold green'
symbol = '👩‍💻 '
format = '[$symbol]($style)'
disabled = false

[terraform]
format = '[🏎💨 $version$workspace]($style) '

[username]
style_user = 'green bold'
style_root = 'black bold'
format = '[@$user]($style) '
disabled = false
show_always = true

[palettes.nord]
dark_blue = '#5E81AC'
blue = '#81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'
gray = '#434C5E'
black = '#2E3440'
white='#D8DEE9'